"""add_study_types_and_strategic_purposes

Revision ID: 9c805d969479
Revises: fb27f68eb720
Create Date: 2026-02-17 17:01:50.761392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c805d969479'
down_revision: Union[str, None] = 'fb27f68eb720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_contexts', sa.Column('strategic_purpose', 
        postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.alter_column('research_contexts', 'study_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_contexts', 'study_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('research_contexts', 'strategic_purpose')
    # ### end Alembic commands ###